config/routes.rb
Mintel::Application.routes.draw do
  resources :rewards

  resources :miners

  get "home/index"

   root :to => "home#index"

end

app/models/miner.rb
class Miner < ActiveRecord::Base
end

app/models/reward.rb
class Reward < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 def guildupdate
	#get json data
	url = URI.parse('http://www.btcguild.com')
	res = Net::HTTP.start(url.host, url.port) {|http|
		http.get('/api.php?api_key=66b2217e699a0f8e0e383f7cc937b4f4')
	}
	#make it magic
	data = res.body
	raw = StringScanner.new(data)
	
	#parse the shit out of it
	
	#REWARD TABLE INFO
	raw.skip_until /"confirmed_rewards":/
	@confirmed = raw.scan_until (/,/)
	@confirmed = @confirmed.to_f
	
	raw.skip_until /"unconfirmed_rewards":/
	@unconfirmed = raw.scan_until (/,/)
	@unconfirmed = @unconfirmed.to_f
	
	raw.skip_until /"estimated_rewards":/
	@estimated = raw.scan_until (/,/)
	@estimated = @estimated.to_f
	
	raw.skip_until /"payouts":/
	@payouts = raw.scan_until (/,/)
	@payouts = @payouts.to_f
	
	#skip
	raw.skip_until /"pool"/
	raw.skip_until /"hash_rate":/
	@poolhash = raw.scan_until (/,/)
	@poolhash = @poolhash.to_f
	
	raw.skip_until /"round_time":"/
	@round = raw.scan_until (/"/)
	@roundtime = @round[0,7]
	
	
	
	#where should this go?
	@total_reward = (@confirmed + @unconfirmed + @estimated)
	
	
	#MINER TABLE INFO

#the chut
	raw.pos(0)
	i = 0
	active = 0
	workers[]
	while raw.eos? == false
		i = i + 1
		raw.skip_until /"hash_rate":/
		start = raw.pos()
		rate = raw.scan_until (/,/)
		rate = rate.to_f
		if rate > 0
			active = active + 1
			numpos = start - 55   #GET ACTUAL NUMBER
			raw.pos(numpos)
			raw.skip_until /{"/  #possible issue
			miner_num = scan_until(/"/)
			workers.push(miner_num)
		end
		
		
		
		#other loop/conditional
		#if rate > 0
		#	start = start - 48
		#	@workernum = raw.scan_until (/"/)
		#		@workernum = @workernum.to_i
				
				
				raw.pos(numpos)
				
				workers.each {|x|
				
				@workernum = x
				
				if x > 1
					numpos = numpos + (x * 114)
				end
				
				raw.skip_until /"worker_name":"/
				@workername = raw.scan_until (/"/)
				@workername = @workername[0,13]
				
				raw.skip_until /"hash_rate":/
				@hash = raw.scan_until (/,/)
				@hash = @hash.to_f
				
				raw.skip_until /"round_shares":/
				@roundsh = raw.scan_until (/,/)
				@roundsh = @roundsh.to_i
				
				raw.skip_until /"round_stales":/
				@roundst = raw.scan_until (/,/)
				@roundst = @roundst.to_i
				
				raw.skip_until /"reset_shares":/
				@resetsh = raw.scan_until (/,/)
				@resetsh = @resetsh.to_i
				
				raw.skip_until /"reset_stales":/
				@resetst = raw.scan_until (/,/)
				@resetst = @resetst.to_i
				
				raw.skip_until /"total_shares":/
				@totalsh = raw.scan_until (/,/)
				@totalsh = @totalsh.to_i
				
				raw.skip_until /"last_share":/
				@lastsh = raw.scan_until (/,/)
				@lastshtime = @lastsh[1,7]
				
				render :saveminer =>
				}
				
			
		end
	end

	
	raw.skip_until /"pool"/
	raw.skip_until /"hash_rate":/
	@poolhash = raw.scan_until (/,/)
	@poolhash = @poolhash.to_f
	
	raw.skip_until /"round_time":"/
	@round = raw.scan_until (/"/)
	@roundtime = @round[0,7]
	
	
	

end

def savereward
	r = reward.new #need to be rewards?
	r.confirmed_rewards = @confirmed
	r.estimated_rewards = @estimated
	r.payouts = @payouts
	r.unconfirmed_rewards = @unconfirmed
	r.pool_hash_rate = @poolhash
	r.round_time = @roundtime
	r.save
	end

def saveminer
	m = miner.new #miners?
	m.worker_num = @workernum
	m.worker_name = @workername
	m.hash_rate = @hash
	m.round_shares = @roundsh
	m.round_stales = @roundst
	m.reset_shares = @resetsh
	m.reset_stales = @resetst
	m.total_shares = @totalsh
	m.last_share = @lastshtime
	
end
end

app/controllers/miners_controller.rb
class MinersController < ApplicationController
  # GET /miners
  # GET /miners.xml
  def index
    @miners = Miner.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @miners }
    end
  end

  # GET /miners/1
  # GET /miners/1.xml
  def show
    @miner = Miner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @miner }
    end
  end

  # GET /miners/new
  # GET /miners/new.xml
  def new
    @miner = Miner.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @miner }
    end
  end

  # GET /miners/1/edit
  def edit
    @miner = Miner.find(params[:id])
  end

  # POST /miners
  # POST /miners.xml
  def create
    @miner = Miner.new(params[:miner])

    respond_to do |format|
      if @miner.save
        format.html { redirect_to(@miner, :notice => 'Miner was successfully created.') }
        format.xml  { render :xml => @miner, :status => :created, :location => @miner }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @miner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /miners/1
  # PUT /miners/1.xml
  def update
    @miner = Miner.find(params[:id])

    respond_to do |format|
      if @miner.update_attributes(params[:miner])
        format.html { redirect_to(@miner, :notice => 'Miner was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @miner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /miners/1
  # DELETE /miners/1.xml
  def destroy
    @miner = Miner.find(params[:id])
    @miner.destroy

    respond_to do |format|
      format.html { redirect_to(miners_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.xml
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.xml
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.xml
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.xml
  def create
    @reward = Reward.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to(@reward, :notice => 'Reward was successfully created.') }
        format.xml  { render :xml => @reward, :status => :created, :location => @reward }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.xml
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to(@reward, :notice => 'Reward was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.xml
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to(rewards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/miners_helper.rb
module MinersHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mintel</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/miners/_form.html.erb
<%= form_for(@miner) do |f| %>
  <% if @miner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@miner.errors.count, "error") %> prohibited this miner from being saved:</h2>

      <ul>
      <% @miner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mintelid %><br />
    <%= f.text_field :mintelid %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :minernum %><br />
    <%= f.text_field :minernum %>
  </div>
  <div class="field">
    <%= f.label :minername %><br />
    <%= f.text_field :minername %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/miners/edit.html.erb
<h1>Editing miner</h1>

<%= render 'form' %>

<%= link_to 'Show', @miner %> |
<%= link_to 'Back', miners_path %>

app/views/miners/index.html.erb
<h1>Listing miners</h1>

<table>
  <tr>
    <th>Mintelid</th>
    <th>Time</th>
    <th>Minernum</th>
    <th>Minername</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @miners.each do |miner| %>
  <tr>
    <td><%= miner.mintelid %></td>
    <td><%= miner.time %></td>
    <td><%= miner.minernum %></td>
    <td><%= miner.minername %></td>
    <td><%= link_to 'Show', miner %></td>
    <td><%= link_to 'Edit', edit_miner_path(miner) %></td>
    <td><%= link_to 'Destroy', miner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Miner', new_miner_path %>

app/views/miners/new.html.erb
<h1>New miner</h1>

<%= render 'form' %>

<%= link_to 'Back', miners_path %>

app/views/miners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mintelid:</b>
  <%= @miner.mintelid %>
</p>

<p>
  <b>Time:</b>
  <%= @miner.time %>
</p>

<p>
  <b>Minernum:</b>
  <%= @miner.minernum %>
</p>

<p>
  <b>Minername:</b>
  <%= @miner.minername %>
</p>


<%= link_to 'Edit', edit_miner_path(@miner) %> |
<%= link_to 'Back', miners_path %>

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :confirmed_reward %><br />
    <%= f.text_field :confirmed_reward %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>Time</th>
    <th>Confirmed reward</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.time %></td>
    <td><%= reward.confirmed_reward %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @reward.time %>
</p>

<p>
  <b>Confirmed reward:</b>
  <%= @reward.confirmed_reward %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>